### ISSUE TITLE
Unable to close accounts owned by a PDA

### ISSUE THREAD

**Issue by aiell0** [blockworks-foundation/mango-v3#171]
### Problem
When a Mango account is created and owned by a Program Derived Address (PDA), it is unable to be closed using the following mango client function:
```
await mangoClient.closeMangoAccount(mg, ma, mangoAccountOwner);
```
where `mangoAccountOwner` is a PDA.

### Steps to Reproduce
1. Create a PDA which is supposed to represent the account owner.
2. Create a Mango account and specify the PDA as the owner (in this case, I did this using a CPI call).
3. Attempt to close the account by specifying the PDA as the owner.

### Error ([transaction](https://explorer.solana.com/tx/5iMZoBqw1PixUFRq4czZksQAkG8bEGLgrrXnSTAh2NgaGxLjEiXH4fsUUrDWkAT2Dt3cYSdyqtZNEwFVm44TzCwJ?cluster=devnet)):
```
> Program log: Mango: CloseMangoAccount
> Program log: MangoErrorCode::InvalidOwner; src/processor.rs:225
> Program 4skJ85cdxQAFVKbcGgfun8iZPL7BadVYXG3kGEGkufqA consumed 2700 of 1400000 compute units
> Program returned error: custom program error: 0x1
> Runtime error: custom program error: 1
```

**Comment by zoheb-mzs** [comment]
Close account instruction should also be called using CPI as the PDA needs to sign...

**Comment by aiell0** [comment]
> Close account instruction should also be called using CPI as the PDA needs to sign...

Thank you for this, the PR can be closed.
